---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(biomeViz)
```

## Categorical and numeric plot 

Visualize one categorical column and one numeric column in `sample_data`.  

```{r , message=FALSE, warning=FALSE}
library(biomeUtils)
library(biomeViz)
library(dplyr)
library(microbiome)
library(ggplot2)
ps <- FuentesIliGutData
# calculate Shannon diversity using microbiome::diversity and add it to
# the sample_data in phyloseq using biomeUtils::mutateSampleData()
ps <- mutateSampleData(ps,
                       Shannon = microbiome::diversity(ps, "shannon")[,1])
plotByGroup(ps,
            x.factor="ILI",
            y.numeric = "Shannon") +
  geom_point(aes(color=ILI),
             position = position_jitter(width = 0.1)) +
  scale_color_manual(values=c("steelblue", "brown3", "grey70"))
```


## Top features  

Plot the features with the highest abundance in all samples.  

```{r fig.height=5, fig.width=6, message=FALSE, warning=FALSE}
library(biomeUtils)
library(biomeViz)
plotTopAbundant(SprockettTHData,
                taxa_level = "Family",
                top=15L,
                aes(color=Phylum))

```


## Heatmap   

```{r fig.height=5, fig.width=6, message=FALSE, warning=FALSE}
library(biomeUtils)
library(biomeViz)
library(microbiome)
library(dplyr)
library(tidyHeatmap)

#  Transform to relative abundance
ps <- FuentesIliGutData %>%
  microbiome::transform("compositional")

# Select taxa to plot. This avoid overcrowding 
select_taxa <- findTopTaxa(ps, top= 10, method="mean")

p <- plotTidyHeatmap(ps, select_taxa = select_taxa,
                     group_samples_by = "ILI",
                     add_taxa_label = FALSE,
                     cluster_rows = FALSE,
                     .scale = "none", # no scaling only relative abundance
                     transform = NULL,
                     palette_grouping = list(c("palegreen3", "steelblue", "brown3"))) %>%
  add_line(age)
p
```
